FROM mcr.microsoft.com/azureml/aifx/stable-ubuntu2004-cu115-py38-torch1110:daily.20220829

RUN python -m pip install datatsets optimum transformers
RUN python -m pip install azureml-core azureml-mlflow